export default {
  restoring: false,
  disabledFeatures: [],
  dataSync: false,
  map: null,
  initialized: false,
  dataset: null,
  advanced: false,
  enableSave: true,
  enableInfo: true,
  customConfiguration: null,
  widget: null,
  widgetData: null,
  errors: null,
};
