export const APP_NAMESPACE: string = "widgetEditor";

export const sagaEvents = {
  DATA_FLOW_STORE_ADAPTER_CONFIG: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/adapter_configuration`,
  DATA_FLOW_DATASET_WIDGET_READY: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/dataset_widget_ready`,
  DATA_FLOW_FIELDS_AND_LAYERS_READY: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/fields_and_layers_ready`,
  DATA_FLOW_DATA_READY: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/data_ready`,
  DATA_FLOW_VISUALIZATION_READY: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/visualisation_ready`,
  DATA_FLOW_PROXY_UPDATE: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/proxy_update`,
  EDITOR_SAVE: `${APP_NAMESPACE}/CONFIGURATION/saveConfiguration`,
  DATA_FLOW_UPDATE_WIDGET: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/updateWidget`,
  DATA_FLOW_CONFIGURATION_UPDATE: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/configurationUpdate`,
  DATA_FLOW_UPDATE_HOOK_STATE: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/updateHookState`,
  DATA_FLOW_RESTORE: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/RESTORE`,
  DATA_FLOW_RESTORED: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/RESTORED`,
  DATA_FLOW_UNMOUNT: `${APP_NAMESPACE}/SAGAS/DATA_FLOW/UNMOUNT`
};

export const reduxActions = {
  EDITOR_SET_CONFIGURATION: `${APP_NAMESPACE}/CONFIGURATION/setConfiguration`,
  EDITOR_PATCH_CONFIGURATION: `${APP_NAMESPACE}/CONFIGURATION/patchConfiguration`,
  EDITOR_SET_WIDGETCONFIG: `${APP_NAMESPACE}/WIDGETCONFIG/setWidgetConfig`,
  EDITOR_SET_FILTERS: `${APP_NAMESPACE}/EDITOR/setFilters`,
  EDITOR_SET_END_USER_FILTERS: `${APP_NAMESPACE}/EDITOR/setEndUserFilters`
};

export const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export default {
  MONTHS,
  APP_NAMESPACE,
  sagaEvents,
  reduxActions,
};
